extern void comment_stmt(void);
extern struct dataset *get_dataset(char *);
extern void get_next_token(void);
extern void print_table(char **, int, int, char *);
extern void print_table_and_free(char **, int, int, char *);
extern void select_dataset(char *);
extern void parse_data_option(void);
extern void parse_proc_print_stmt(void);
extern void parse_proc_print_body(void);
extern void run_proc_print(void);
extern void parse_proc_means_stmt(void);
extern void parse_proc_means_body(void);
extern void run_proc_means(void);
extern void print_title(void);
extern void proc_anova(void);
extern void proc_means(void);
extern void proc_print(void);
extern void proc_reg(void);
extern void regress(void);
extern void print_anova_table(void);
extern void print_diag_table(void);
extern void print_parameter_estimates(void);
extern void emit_line(char *);
extern void emit_line_center(char *);
extern double tdist(double, double);
extern double fdist(double, double, double);
extern void parse_alpha_option(void);
